Add/Edit Log Point: Scroll line into view (#8198)
devtools-html/debugger.html pull request #8199
Opened 2019-04-22 22:52 UTC by Archaeopteryx

Fixes #8198 

Here's the Pull Request Doc
https://firefox-dev.tools/debugger/docs/pull-requests.html

### Summary of Changes

* Scroll line into view if a log point shall be added to it or an existing one be edited.

### Test Plan

Tested with a Firefox Nightly artifact build.

Example test plan:

1. Open https://freshman.tech/calculator/
2. Open the debugger.
3. In the left sidebar, open https://jsfiddle.net/js/embed/embed.js
4. Go to line 25, set a breakpoint.
5. Scroll to the top.
6. Check that line 25 is not shown.
7. In the right sidebar, right-click the breakpoint.
8. Choose 'Add log'.

Expected result: Line 25 scrolled into view and text field for adding log point visible.

2019-04-23 04:16 UTC, jasonLaster reviewed
Nice fix!

2019-04-23 04:16 UTC, jasonLaster commented on src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js
> +      selectSpecificLocation(cx, selectedLocation);
Minor detail. I think we should dispatch select inside of open conditional

2019-04-23 14:58 UTC, darkwing requested changes
Just needs a quick update per Jason's feedback :)

2019-05-11 15:06 UTC, AnshulMalik commented
Any updates on this @Archaeopteryx ?

2021-03-02 12:26 UTC, janodvarko reviewed
The patch doesn't fix the problem for me, so I am closing it.

But, I cloned the issue into Bugzilla here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1695896

I am happy to review new version of the patch in Bugzilla.
Thank you!

2021-03-02 12:28 UTC, janodvarko commented
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza

2021-03-02 12:28 UTC, closed without merging